---
# vars file for deploy_ror
DEPLOYMENT_PORT: APPLICATION_PORT
RAILS_ENV: RAILS_ENVIRONMENT
RAILS_SERVE_STATIC_FILES: ANSWER_SERVE
APPLICATION_NAME: APP_NAME 
APPLICATION_SOURCE: WORKDIR
APPLICATION_DEST: /home/{{ rails_user }}
CONFIGURE_HOST_NODE_EXPORTERS: ANSWER