---
- hosts: localhost

  vars:
    PRODUCTION_HOST_1: "{{ groups['production'][0] }}"
    PRODUCTION_HOST_2: "{{ groups['production'][1] }}"
    PRODUCTION_HOST_3: "{{ groups['production'][2] }}"
    PRODUCTION_HOST_4: "{{ groups['production'][3] }}"
    PRODUCTION_HOST_5: "{{ groups['production'][4] }}"

  pre_tasks:

    - name: Install epel-release to RedHat OS
      raw: yum install epel-release -y
      when: ansible_distribution == 'CentOS'

    - name: Check or install needed Python versions on RedHat OS
      raw: yum install python python-pip python3 python3-pip -y
      when: ansible_distribution == 'CentOS'

    - name: Check or install needed Python versions on Debian/Ubuntu OS
      raw: sudo apt-get install python python-pip python3 python3-pip -y
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- hosts: production

  pre_tasks:

    - name: Import Prereq tasks
      include: prereq_tasks.yml
      
- hosts: production
  become: yes

  tasks:
  
    - name: Check installed rvm
      block:
  
      - name: Check installed rvm
        command: rvm list
      
      rescue:
      - name: Include install rvm tasks
        become: true
        remote_user: "{{ rails_user }}"
        become_user: "{{ ansible_user }}"
        include: install_rvm.yml
      
    - name: Copy Application files to remote hosts
      synchronize:
        src: '{{ APPLICATION_SOURCE }}'
        dest: '{{ APPLICATION_DEST }}'
    
    - name: Export variables tasks
      include: export_variables.yml

    - name: Install application
      become: true
      remote_user: "{{ rails_user }}"
      become_user: "{{ ansible_user }}"
      include: install_app.yml

    - name: Check existing of prometheus exporter config file
      command: 'cat {{ APPLICATION_DEST }}/{{ APPLICATION_NAME }}/config/initializers/prometheus.rb'
      ignore_errors: yes
      register: checkkey
      args:
        chdir: '{{ APPLICATION_DEST }}/{{ APPLICATION_NAME }}'
      
    - name: Copy and start systemd files
      become: true
      remote_user: "{{ rails_user }}"
      become_user: "{{ ansible_user }}"
      include: systemd.yml

    - name: Run simple application healthchecks
      uri:
        url: http://localhost:{{ DEPLOYMENT_PORT }}
      
    - name: Check prometheus metrics
      uri:
        url: http://localhost:9394/metrics
      when: checkkey is not failed

    - name: Add prometheus node_exporter to production host
      become: true
      remote_user: "{{ rails_user }}"
      become_user: "{{ ansible_user }}"
      include: node_exporter.yml
      when: 
        - checkkey is not failed
        - CONFIGURE_HOST_NODE_EXPORTERS | bool

    - debug:
        msg: Application successfully deployed
      when: service_output.changed
