---
- hosts: localhost

  pre_tasks:

    - name: Check existing python version on host
      raw: python --version
      ignore_errors: yes
      register: python_exist

    - name: Install epel-release to RedHat OS
      raw: yum install epel-release -y
      when: 
        - ansible_distribution == 'CentOS'
        - python_exist.rc > 0

    - name: Install needed Python versions on RedHat OS
      raw: yum install python python-pip python3 python3-pip -y
      when: 
        - ansible_distribution == 'CentOS'
        - python_exist.rc > 0

    - name: Install needed Python versions on Debian/Ubuntu OS
      raw: sudo apt-get install python python-pip python3 python3-pip -y
      when: 
        - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
        - python_exist.rc > 0

- hosts: production

  pre_tasks:

    - name: Check existing systemd file with app
      shell: systemctl status {{ APPLICATION_NAME }} | grep Active
      ignore_errors: yes
      register: app_systemd_exist

    - name: Import Prereq tasks
      include: prereq_tasks.yml
      when: app_systemd_exist.rc > 0

    - name: Check installed rvm
      block:
  
      - name: Check installed rvm
        remote_user: "{{ rails_user }}"
        command: rvm list
        when: app_systemd_exist.rc > 0
      
      rescue:
      - name: Include install rvm tasks
        become: true
        remote_user: "{{ rails_user }}"
        become_user: "{{ ansible_user }}"
        include: install_rvm.yml
        when: app_systemd_exist.rc > 0
      
- hosts: production
  become: yes

  tasks:
      
    - name: Copy Application files to remote hosts
      remote_user: "{{ rails_user }}"
      synchronize:
        src: '{{ APPLICATION_SOURCE }}'
        dest: '{{ APPLICATION_DEST }}'
    
    - name: Change file ownership, group and permissions
      file:
        path: "{{ APPLICATION_DEST }}/{{ APPLICATION_NAME }}"
        owner: "{{ rails_user }}"
        group: wheel
        recurse: yes

    - name: Export variables tasks
      remote_user: "{{ rails_user }}"
      include: export_variables.yml

    - name: Install application
      become: true
      remote_user: "{{ rails_user }}"
      become_user: "{{ ansible_user }}"
      include: install_app.yml

    - name: Check existing of prometheus exporter config file
      remote_user: "{{ rails_user }}"
      command: 'cat {{ APPLICATION_DEST }}/{{ APPLICATION_NAME }}/config/initializers/prometheus.rb'
      ignore_errors: yes
      register: checkkey
      args:
        chdir: '{{ APPLICATION_DEST }}/{{ APPLICATION_NAME }}'
      
    - name: Copy and start systemd files
      become: true
      remote_user: "{{ rails_user }}"
      become_user: "{{ ansible_user }}"
      include: systemd.yml

    - pause:
        seconds: 20

    - name: Run simple application healthchecks
      remote_user: "{{ rails_user }}"
      uri:
        url: http://localhost:{{ DEPLOYMENT_PORT }}
      
    - name: Check prometheus metrics
      remote_user: "{{ rails_user }}"
      uri:
        url: http://localhost:9394/metrics
      when: checkkey is not failed

    - name: Add prometheus node_exporter to production host
      become: true
      remote_user: "{{ rails_user }}"
      become_user: "{{ ansible_user }}"
      include: node_exporter.yml
      when: 
        - checkkey is not failed
        - CONFIGURE_HOST_NODE_EXPORTERS | bool

    - debug:
        msg: Application successfully deployed
      when: service_output.changed
